# Site settings
title: Gaussian See, Gaussian Do
description: 3D Semantic Motion Transfer
author: Your Name

# Build settings
theme: minima
markdown: kramdown

# Social links (optional)
github_username: yourusername
# twitter_username: yourusername

# Additional settings
show_excerpts: true
header_pages:
  - about.md 